### ISSUE TITLE
BIG BUG

### ISSUE THREAD

**Issue by matthew4444** [UniversalMine/PC-Client-Base#5]
look heres what happens when I use the plugin and the server:
13:35:57 | UniversalMine:INFO -> Saving levels...
13:35:57 | UniversalMine:INFO -> Reloading properties...
13:35:57 | UniversalMine:INFO -> Loading BigBrother v1.0.0
13:35:58 | UniversalMine:INFO -> Enabling BigBrother v1.0.0
13:35:58 | UniversalMine:INFO -> [BigBrother] Starting Minecraft: PC server on *:25565 version 1.8
13:35:58 | UniversalMine:INFO -> [CONSOLE: Reload complete.]
Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in C:\Users\MatthewJP\Downloads\genisys-serverrrrr\src\shoghicp\BigBrother\network\translation\TranslatorProtocol.php on line 622
Warning: Invalid argument supplied for foreach() in C:\Users\MatthewJP\Downloads\genisys-serverrrrr\src\shoghicp\BigBrother\network\translation\TranslatorProtocol.php on line 622
13:36:06 | UniversalMine:CRITICAL -> [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Undefined class constant 'REPLACE_SELECTED_ITEM_PACKET'
[Send] 0x31
Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in C:\Users\MatthewJP\Downloads\genisys-serverrrrr\src\shoghicp\BigBrother\network\translation\TranslatorProtocol.php on line 622
Warning: Invalid argument supplied for foreach() in C:\Users\MatthewJP\Downloads\genisys-serverrrrr\src\shoghicp\BigBrother\network\translation\TranslatorProtocol.php on line 622
[Send] 0x55
[Send] 0x52
[Send] 0x52
13:36:06 | UniversalMine:INFO -> MatthewJP joined the game
Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in C:\Users\MatthewJP\Downloads\genisys-serverrrrr\src\shoghicp\BigBrother\network\translation\TranslatorProtocol.php on line 622
Warning: Invalid argument supplied for foreach() in C:\Users\MatthewJP\Downloads\genisys-serverrrrr\src\shoghicp\BigBrother\network\translation\TranslatorProtocol.php on line 622

and it tells me disconcted on pc client.
and when I rejoin it says conntection refused, plz help

**Comment by erkam2002** [comment]
Dont reload

**Comment by matthew4444** [comment]
ok

**Comment by Driesboy** [comment]
dont use genisys!

**Comment by Driesboy** [comment]
i need to recode this fully

**Comment by matthew4444** [comment]
what do I use then, I just sent a copy to hitmana, and its based from gennisys, aka universsalmine

**Comment by Driesboy** [comment]
elywings its the only full compatible 1.0 update

**Comment by matthew4444** [comment]
the client base plugin is suposta be compactble with mc 1.8.8 with pic from @red

**Comment by matthew4444** [comment]
@RedstoneAlmeida

**Comment by HittmanA** [comment]
Ok so what should I do

**Comment by HittmanA** [comment]
I cant use MCPC cause I forgot my password

**Comment by matthew4444** [comment]
we need to fix the pc client base plugin based from my crashdump, and heres the free MCPc link

**Comment by matthew4444** [comment]
do u have java ?

**Comment by HittmanA** [comment]
yes

**Comment by matthew4444** [comment]
https://drive.google.com/file/d/0B36vPr6onNjiR040dloydWwxUWc/view?usp=sharing

**Comment by matthew4444** [comment]
here u go

**Comment by HittmanA** [comment]
thx

**Comment by matthew4444** [comment]
tell me if it works

**Comment by HittmanA** [comment]
ok

**Comment by HittmanA** [comment]
It works

**Comment by HittmanA** [comment]
Ok so what do I need to join from PC?

**Comment by matthew4444** [comment]
is it downloading minecraft based from 1.8.8

**Comment by matthew4444** [comment]
download mc 1.8.8

**Comment by matthew4444** [comment]
and ip is 127.0.0.1

**Comment by HittmanA** [comment]
no it is 1.12.1

**Comment by HittmanA** [comment]
sorry 1.11.2

**Comment by matthew4444** [comment]
the portcal for plugin base is 1.11.2?

**Comment by matthew4444** [comment]
prootacal

**Comment by HittmanA** [comment]
no I got mc 1.11.2

**Comment by matthew4444** [comment]
select 1.8.8 from the list

**Comment by HittmanA** [comment]
ok

**Comment by matthew4444** [comment]
because we made it for that version

**Comment by HittmanA** [comment]
It should be compatible with many versions

**Comment by matthew4444** [comment]
every version they change protocal

**Comment by HittmanA** [comment]
oh

**Comment by matthew4444** [comment]
kkk, download 1.8.8 plz

**Comment by HittmanA** [comment]
I did

**Comment by HittmanA** [comment]
Now what do i need to be able to join?

**Comment by matthew4444** [comment]
is it on ur screen, the game

**Comment by HittmanA** [comment]
yes

**Comment by matthew4444** [comment]
then the ip is 127.0.0.1

**Comment by HittmanA** [comment]
What plugin do I need to play from pc?

**Comment by HittmanA** [comment]
yes it is

**Comment by matthew4444** [comment]
and wath the server console to. and here https://drive.google.com/file/d/0B36vPr6onNjiaENEVE9nZ2dJWjA/view?usp=sharing

**Comment by matthew4444** [comment]
move the phar to the plugins folder, and type reload in to the console

**Comment by HittmanA** [comment]
ok but shouldnt the pc bridge be built in. Not a plugin?

**Comment by matthew4444** [comment]
that's what I tought

**Comment by HittmanA** [comment]
Then why don't we build it in?

**Comment by matthew4444** [comment]
can u do that

**Comment by matthew4444** [comment]
in a new repo

**Comment by HittmanA** [comment]
I will try

**Comment by matthew4444** [comment]
it only will work wwith mcregion worlds by the way

**Comment by HittmanA** [comment]
BTW i get this in console:

```
Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622

Warning: Invalid argument supplied for foreach() in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622
20:11:29 | UniversalMine:CRITICAL -> [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Undefined class constant 'REPLACE_SELECTED_ITEM_PACKET'
[Send] 0x31

Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622

Warning: Invalid argument supplied for foreach() in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622
[Send] 0x55
[Send] 0x52
[Send] 0x52
20:11:29 | UniversalMine:INFO -> Hittmana joined the game

Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622

Warning: Invalid argument supplied for foreach() in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622
```

**Comment by matthew4444** [comment]
can u fix that?

**Comment by HittmanA** [comment]
Hmmmm

**Comment by matthew4444** [comment]
I get it to

**Comment by HittmanA** [comment]
I will try

**Comment by matthew4444** [comment]
thx that's all I need is for u to fix the bug u just got

**Comment by HittmanA** [comment]
K

**Comment by matthew4444** [comment]
tell us in this big bug post when u fix it plz

**Comment by HittmanA** [comment]
Ok

**Comment by HittmanA** [comment]
Where can I see a list of available packets

**Comment by HittmanA** [comment]
anyone?

**Comment by HittmanA** [comment]
Making some progress

**Comment by HittmanA** [comment]
Ok so I fixed one packet. 2 more to go

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
hello?

**Comment by HittmanA** [comment]
What is wrong with this: 
```
foreach($packet->entities as $d){
}```

**Comment by matthew4444** [comment]
umm let me try to check?

**Comment by matthew4444** [comment]
I used a php checker and found this PHP Syntax Check: Parse error: syntax error, unexpected '`' in your code on line 2
}```
PHP Syntax Check: Errors parsing your code

**Comment by matthew4444** [comment]
hello?

**Comment by HittmanA** [comment]
Ik that

**Comment by HittmanA** [comment]
nvm

**Comment by matthew4444** [comment]
u found the erroer?

**Comment by HittmanA** [comment]
yes

**Comment by matthew4444** [comment]
when u finish the project can u upload it to GitHub , and correct it in the universalmine pc-client base repo?

**Comment by HittmanA** [comment]
yes

**Comment by matthew4444** [comment]
thx

**Comment by matthew4444** [comment]
tell us when u got the other packets done., say each one at a time plz?

**Comment by HittmanA** [comment]
Ok

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
u there?

**Comment by HittmanA** [comment]
Yes

**Comment by matthew4444** [comment]
how long till the second packet, is done? estimated time

**Comment by HittmanA** [comment]
Idk

**Comment by HittmanA** [comment]
Depends

**Comment by matthew4444** [comment]
are u half way there?

**Comment by matthew4444** [comment]
are u half way there?

**Comment by HittmanA** [comment]
Idk

**Comment by matthew4444** [comment]
can u finish on packet 2

**Comment by HittmanA** [comment]
I am trying!

**Comment by matthew4444** [comment]
what is after the ppackets in the plugin?

**Comment by HittmanA** [comment]
Nothing

**Comment by matthew4444** [comment]
ok. keep up the good work and tell me when packet 2 is done

**Comment by HittmanA** [comment]
k

**Comment by RedstoneAlmeida** [comment]
Bug for REPLACED_ITEM is fixed, in last version's

**Comment by matthew4444** [comment]
I couldng join with it

**Comment by matthew4444** [comment]
there was packetbugs

**Comment by matthew4444** [comment]
shes on packet 2/3 , we found the bugs were almost done

**Comment by RedstoneAlmeida** [comment]
Chat from 1.8.8 is done in json, I have not finished adding it yet

**Comment by matthew4444** [comment]
wait for her to finish , then compare and check for bugs, and modify code if needed

**Comment by RedstoneAlmeida** [comment]
It's complicated, but it's possible to pack it should be some wrong sending packet

**Comment by matthew4444** [comment]
when @HittmanA finishes , u (@redstoneAlemdia)and hittmana can review and modify code, on GitHub repo

**Comment by RedstoneAlmeida** [comment]
okay, i'm is working on ASync generation for PC

**Comment by matthew4444** [comment]
thx

**Comment by HittmanA** [comment]
I am a he @matthew4444

**Comment by matthew4444** [comment]
ohh

**Comment by matthew4444** [comment]
sorry

**Comment by matthew4444** [comment]
:(

**Comment by matthew4444** [comment]
u there

**Comment by matthew4444** [comment]
?

**Comment by HittmanA** [comment]
its ok

**Comment by matthew4444** [comment]
u on the second packet still?

**Comment by HittmanA** [comment]
Yes. I am having trouble understanding the errors

**Comment by matthew4444** [comment]
what error?

**Comment by HittmanA** [comment]
```
Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622

Warning: Invalid argument supplied for foreach() in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622
21:08:09 | UniversalMine:CRITICAL -> [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Undefined class constant 'REPLACE_SELECTED_ITEM_PACKET'

**Comment by matthew4444** [comment]
does this help? http://docs.pocketmine.net/da/dec/classpocketmine_1_1network_1_1protocol_1_1_set_entity_motion_packet.html

**Comment by HittmanA** [comment]
let me check

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
do u see any eroors?

**Comment by HittmanA** [comment]
where?

**Comment by matthew4444** [comment]
I thought u said:
Notice: Undefined property: pocketmine\network\protocol\SetEntityMotionPacket::$entities in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622

Warning: Invalid argument supplied for foreach() in /Users/austinhitt/Desktop/genisys-serverrrrr/src/shoghicp/BigBrother/network/translation/TranslatorProtocol.php on line 622
21:08:09 | UniversalMine:CRITICAL -> [Network] Stopped interface shoghicp\BigBrother\network\ProtocolInterface due to Undefined class constant 'REPLACE_SELECTED_ITEM_PACKET'

**Comment by HittmanA** [comment]
oh yeah

**Comment by matthew4444** [comment]
u find the eroor?

**Comment by HittmanA** [comment]
Idk how to fix it but i am trying

**Comment by matthew4444** [comment]
ok

**Comment by RedstoneAlmeida** [comment]
use

```php
                        case Info::SET_ENTITY_DATA_PACKET:
				$pk = new EntityMetadataPacket();
				$pk->eid = $packet->eid;
				$pk->metadata = $packet->metadata;
				return $pk;
```

**Comment by HittmanA** [comment]
k I will try that

**Comment by matthew4444** [comment]
thx

**Comment by HittmanA** [comment]
What will that do?

**Comment by RedstoneAlmeida** [comment]
Download last version, She has more stability

**Comment by matthew4444** [comment]
something with who spawns "packet"

**Comment by RedstoneAlmeida** [comment]
Will prevent crash's current

**Comment by HittmanA** [comment]
ok

**Comment by HittmanA** [comment]
Did nothing

**Comment by matthew4444** [comment]
tell us if it works @HittmanA

**Comment by matthew4444** [comment]
what?

**Comment by HittmanA** [comment]
Yep same errors

**Comment by matthew4444** [comment]
????????????????????????????????//

**Comment by matthew4444** [comment]
@RedstoneAlmeida it didn't work

**Comment by RedstoneAlmeida** [comment]
are you sure? In the most current version of the bug not just some light bugs that I'm still fixing

**Comment by HittmanA** [comment]
Yep

**Comment by RedstoneAlmeida** [comment]
faça o download e teste: https://github.com/UniversalMine/PC-Client-Base/archive/master.zip

**Comment by HittmanA** [comment]
ok hang on

**Comment by matthew4444** [comment]
ill translate that

**Comment by matthew4444** [comment]
ill translate that

**Comment by HittmanA** [comment]
ok

**Comment by RedstoneAlmeida** [comment]
Excuse me, I'm not used to speaking English.

**Comment by matthew4444** [comment]
shes said":
Download and test: https://github.com/UniversalMine/PC-Client-Base/archive/master.zip

**Comment by HittmanA** [comment]
ok

**Comment by matthew4444** [comment]
does it work

**Comment by HittmanA** [comment]
i am about to test

**Comment by matthew4444** [comment]
kk

**Comment by HittmanA** [comment]
I get the same errors @RedstoneAlmeida

**Comment by RedstoneAlmeida** [comment]
I always send the versions that work from my computer to the repository, almost sure it works

**Comment by matthew4444** [comment]
what server software are u using @RedstoneAlmeida

**Comment by RedstoneAlmeida** [comment]
as well? Are you at 0.16 or 1.0?

**Comment by matthew4444** [comment]
universalmine 1.0

**Comment by HittmanA** [comment]
?

**Comment by matthew4444** [comment]
shes has univeralmine 1.0 and me

**Comment by RedstoneAlmeida** [comment]
Use Elywing or Genisys (0.16)

**Comment by RedstoneAlmeida** [comment]
Elywing = 1.0
Genisys = 0.16

**Comment by matthew4444** [comment]
ok ill trry

**Comment by HittmanA** [comment]
@RedstoneAlmeida the plugin does not work

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/21753707/a9f7be30-d5d9-11e6-907d-381605c1fde5.png)
- No Errors

**Comment by matthew4444** [comment]
look I found https://github.com/H4PM/Elywing/commit/4a09e1353dbac5bdcec7a988fed7456dbf78cca4

**Comment by HittmanA** [comment]
I am using UniversalMine @RedstoneAlmeida

**Comment by HittmanA** [comment]
why doesn't it work?

**Comment by RedstoneAlmeida** [comment]
I'm using Genisys 0.16

**Comment by matthew4444** [comment]
can u send me the entire pocketmine folder with src and plugins and worlds and etc as zip plz , so I can test it?

**Comment by matthew4444** [comment]
@RedstoneAlmeida

**Comment by RedstoneAlmeida** [comment]
Okay, 1 Moment

**Comment by matthew4444** [comment]
thx

**Comment by HittmanA** [comment]
@RedstoneAlmeida why doesn't it work for UniversalMine though?

**Comment by RedstoneAlmeida** [comment]
Nao faço ideia, não testei ainda :c

**Comment by RedstoneAlmeida** [comment]
I have no idea, I have not tested it yet****

**Comment by RedstoneAlmeida** [comment]
download: https://github.com/UniversalMine/PC-Client-Base/blob/master/Media/BigBrother.zip

**Comment by HittmanA** [comment]
oh

**Comment by HittmanA** [comment]
why @RedstoneAlmeida

**Comment by matthew4444** [comment]
u said u didn't test it, but u sent this https://cloud.githubusercontent.com/assets/15146680/21753707/a9f7be30-d5d9-11e6-907d-381605c1fde5.png

**Comment by matthew4444** [comment]
??

**Comment by matthew4444** [comment]
hello?

**Comment by HittmanA** [comment]
Back

**Comment by RedstoneAlmeida** [comment]
download my source plugins, world and src: https://github.com/UniversalMine/PC-Client-Base/blob/master/Media/BigBrother.zip

**Comment by matthew4444** [comment]
does that zip workk

**Comment by matthew4444** [comment]
the zip works, t

**Comment by matthew4444** [comment]
thx

**Comment by matthew4444** [comment]
does placing blocks wok @RedstoneAlmeida

**Comment by matthew4444** [comment]
placing blocks isn't being recooonized by the server


 Notice: Uninitialized string offset: 25 in C:\Users\MatthewJP\Downloads\server2\genisys-serverrrrr\plugins\BigDrother\src\shoghicp\BigBrother\network\Packet.php on line 110

plz fix

**Comment by RedstoneAlmeida** [comment]
I do not handle a lot of packets :(

**Comment by matthew4444** [comment]
what that mean?
